"""Слой решения: кандидаты CV и признаки этикетки → один slug каталога или отказ."""

from app.resolve.ambiguous import (
    CLUSTER_FEATURE,
    contradicts,
    rerank_ambiguous,
)
from app.resolve.attrs import (
    CONDITIONAL_NAME_FLAGS,
    CatalogAttrs,
    WineAttrs,
    abv_key,
    color_key,
    default_attrs_path,
    grape_key,
    load_attrs,
    norm_key,
    serial_key,
    sugar_key,
    wine_attrs,
    year_key,
)
from app.resolve.rerank import (
    DEFAULT_CONFIG,
    FEATURES,
    WEIGHTS_NOTE,
    AbstainMode,
    Agreement,
    Feature,
    FeatureWeights,
    Outcome,
    ReadKeys,
    RerankConfig,
    ResolveResult,
    abstain_check,
    agreement,
    read_fields,
    rerank,
    score_wine,
)

__all__ = [
    "CLUSTER_FEATURE",
    "CONDITIONAL_NAME_FLAGS",
    "DEFAULT_CONFIG",
    "FEATURES",
    "WEIGHTS_NOTE",
    "AbstainMode",
    "Agreement",
    "CatalogAttrs",
    "Feature",
    "FeatureWeights",
    "Outcome",
    "ReadKeys",
    "RerankConfig",
    "ResolveResult",
    "WineAttrs",
    "abstain_check",
    "abv_key",
    "agreement",
    "color_key",
    "contradicts",
    "default_attrs_path",
    "grape_key",
    "load_attrs",
    "norm_key",
    "read_fields",
    "rerank",
    "rerank_ambiguous",
    "score_wine",
    "serial_key",
    "sugar_key",
    "wine_attrs",
    "year_key",
]
