"""Закрытый словарь каталога: сборка из `gt_tokens.jsonl` и поиск фрагментов этикетки."""

from app.reading.lexicon.build import (
    COLOR_TERMS,
    FIELDS,
    GENERIC_WORDS,
    SERIAL_TERMS,
    SUGAR_TERMS,
    LexEntry,
    Lexicon,
    build_from_gt,
    build_from_records,
    default_gt_tokens_path,
    default_lexicon_path,
    entry_norm,
    idf,
    load_lexicon,
    read_gt_tokens,
)
from app.reading.lexicon.correct import (
    CONFUSIONS,
    LABEL_STOP_WORDS,
    PHRASE_SERVICE_WORDS,
    LookupResult,
    cost_budget,
    fold_key,
    lookup,
    search,
    unmatched,
    weighted_distance,
)

__all__ = [
    "COLOR_TERMS",
    "CONFUSIONS",
    "FIELDS",
    "GENERIC_WORDS",
    "LABEL_STOP_WORDS",
    "PHRASE_SERVICE_WORDS",
    "SERIAL_TERMS",
    "SUGAR_TERMS",
    "LexEntry",
    "Lexicon",
    "LookupResult",
    "build_from_gt",
    "build_from_records",
    "cost_budget",
    "default_gt_tokens_path",
    "default_lexicon_path",
    "entry_norm",
    "fold_key",
    "idf",
    "load_lexicon",
    "lookup",
    "read_gt_tokens",
    "search",
    "unmatched",
    "weighted_distance",
]
